mysite/blog/urls.py
from django.urls import path

from . import feeds, views

app_name = "blog"


urlpatterns = [
    path("", views.post_list, name="post_list"),
    path("tag/<slug:tag_slug>/", views.post_list, name="post_list_by_tag"),
    # path("", views.PostListView.as_view(), name="post_list"),
    path(
        "<int:year>/<int:month>/<int:day>/<slug:slug>/",
        views.post_detail,
        name="post_detail",
    ),
    path("<int:post_id>/share/", views.post_share, name="post_share"),
    path("<int:post_id>/comment/", views.post_comment, name="post_comment"),
    path("feed/", feeds.LatestPostsFeed(), name="post_feed"),
    path("search/", views.post_search, name="post_search"),
]

mysite/mysite/urls.py
from blog.sitemaps import PostSitemap
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path

sitemaps = {
    "posts": PostSitemap,
}


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("blog.urls", namespace="blog")),
    path("blog/", include("blog.urls", namespace="blog")),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
]

mysite/blog/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils import timezone
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    def get_queryset(self) -> models.QuerySet:
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)


class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = "DF", "Draft"
        PUBLISHED = "PB", "Published"

    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date="publish")
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="blog_posts",
    )
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(
        max_length=2, choices=Status.choices, default=Status.DRAFT
    )

    objects = models.Manager()
    published = PublishedManager()

    tags = TaggableManager()

    class Meta:
        ordering = ["-publish"]
        indexes = [
            models.Index(fields=["-publish"]),
        ]

    def __str__(self) -> str:
        return self.title.__str__()

    def get_absolute_url(self) -> str:
        return reverse(
            "blog:post_detail",
            args=[
                self.publish.year,
                self.publish.month,
                self.publish.day,
                self.slug,
            ],
        )


class Comment(models.Model):
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name="comments"
    )
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ["-created"]
        indexes = [models.Index(fields=["-created"])]

    def __str__(self) -> str:
        return f"Comment by {self.name} on {self.post}"

mysite/blog/forms.py
from django import forms

from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["name", "email", "body"]


class SearchForm(forms.Form):
    query = forms.CharField()

mysite/blog/views.py
from typing import Optional

from django.contrib.postgres.search import (
    SearchQuery,
    SearchRank,
    SearchVector,
    TrigramSimilarity,
)
from django.core.mail import send_mail
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Count, F, Q
from django.http import HttpRequest, HttpResponse
from django.shortcuts import get_object_or_404, render
from django.views.decorators.http import require_POST
from django.views.generic import ListView
from taggit.models import Tag

from .forms import CommentForm, EmailPostForm, SearchForm
from .models import Comment, Post


class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = "posts"
    paginate_by = 2
    template_name = "blog/post/list.html"


def post_list(
    request: HttpRequest, tag_slug: Optional[str] = None
) -> HttpResponse:
    post_list = Post.published.all()

    tag = get_object_or_404(Tag, slug=tag_slug) if tag_slug else None
    if tag:
        post_list = post_list.filter(tags__in=[tag])

    paginator = Paginator(post_list, per_page=5)
    page_number = request.GET.get("page", 1)

    try:
        posts = paginator.page(page_number)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    except PageNotAnInteger:
        posts = paginator.page(1)

    context = {"posts": posts, "tag": tag}
    return render(request, "blog/post/list.html", context)


def post_detail(
    request: HttpRequest, year: int, month: int, day: int, slug: str
) -> HttpResponse:
    post = get_object_or_404(
        Post,
        publish__year=year,
        publish__month=month,
        publish__day=day,
        slug=slug,
        status=Post.Status.PUBLISHED,
    )
    comments = Comment.objects.filter(post=post, active=True).all()
    form = CommentForm()

    post_tags_ids = post.tags.values_list("id", flat=True)
    similar_posts = (
        Post.published.filter(tags__in=post_tags_ids)
        .exclude(id=post.id)
        .annotate(same_tags=Count("tags"))
        .order_by("-same_tags", "-publish")[:4]
    )

    context = {
        "post": post,
        "comments": comments,
        "form": form,
        "similar_posts": similar_posts,
    }
    return render(request, "blog/post/detail.html", context)


@require_POST
def post_comment(request: HttpRequest, post_id: int) -> HttpResponse:
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    comment = None

    form = CommentForm(data=request.POST)

    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()

    context = {"post": post, "form": form, "comment": comment}
    return render(request, "blog/post/comment.html", context)


def post_share(request: HttpRequest, post_id: int) -> HttpResponse:
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    sent = False

    if request.method != "POST":
        form = EmailPostForm()
    else:
        form = EmailPostForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            name, email, to, comments = (
                data["name"],
                data["email"],
                data["to"],
                data["comments"],
            )
            post_url = request.build_absolute_uri(post.get_absolute_url())

            subject = f"{name} ({email}) recommends you read {post.title}"
            message = f"Read {post.title} at {post_url}\n\n{name}'s comments: {comments}"

            send_mail(
                subject=subject,
                message=message,
                from_email=None,
                recipient_list=[to],
            )
            sent = True

    context = {"post": post, "form": form, "sent": sent}
    return render(request, "blog/post/share.html", context)


def post_search(request: HttpRequest) -> HttpResponse:
    query = request.GET.get("query")
    form = SearchForm(request.GET or None)
    results = []

    if query and form.is_valid():
        query = form.cleaned_data["query"]
        vector = SearchVector("title", weight="A") + SearchVector(
            "body", weight="B"
        )
        search_query = SearchQuery(query)
        results = (
            Post.published.annotate(
                rank=SearchRank(vector, search_query),
                trigram_title=TrigramSimilarity("title", query),
                trigram_body=TrigramSimilarity("body", query),
            )
            .filter(
                Q(rank__gte=0.1)
                | Q(trigram_title__gte=0.3)
                | Q(trigram_body__gte=0.3)
            )
            .annotate(score=F("rank") + F("trigram_title") + F("trigram_body"))
            .order_by("-score")
        )

    context = {"form": form, "query": query, "results": results}
    return render(request, "blog/post/search.html", context)

mysite/blog/templates/blog/base.html
{% load blog_tags %}
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <title>
            {% block title %}{% endblock %}
        </title>
        <link href="{% static "css/blog.css" %}" rel="stylesheet" />
    </head>
    <body>
        <div id="content">
            {% block content %}{% endblock %}
        </div>
        <div id="sidebar">
            <h2>
                <a href="/">My blog</a>
            </h2>
            <p>This is my blog.</p>
            <p>
                There are {% total_posts %} posts so far.
            </p
            <p>
                <a href="{% url "blog:post_feed" %}">RSS feed</a>
            </p>
            <h3>Latest posts</h3>
            {% show_latest_posts 3 %}
            <h3>Most commented posts</h3>
            {% get_most_commented_posts as mp_posts %}
            <ul>
                {% for post in mp_posts %}
                    <li>
                        <a href="{{ post.get_absolute.url }}">{{ post.title }}</a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </body>
</html>

mysite/blog/templates/blog/post/comment.html
{% extends "blog/base.html" %}

{% block title %}Add a comment{% endblock %}
{% block content %}
    {% if comment %}
        <h2>Your comment has been added.</h2>
        <p>
            <a href="{{ post.get_absolute_url }}">Back to the post</a>
        </p>
    {% else %}

        {% include "blog/post/includes/comment_form.html" %}

    {% endif %}
{% endblock %}

mysite/blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}

{% load blog_tags %}

{% block title %}{{ post.title }}{% endblock %}
{% block content %}
    <h1>{{ post.title }}</h1>
    <p class="date">Published {{ post.publish }} by {{ post.author }}</p>
    {{ post.body|markdown }}
    <p>
        <a href="{% url "blog:post_share" post.id %}">Share this post</a>
    </p>
    <h2>Similar posts</h2>
    {% for post in similar_posts %}
        <p>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </p>
    {% empty %}
        <p>There are no similar posts yet.</p>
    {% endfor %}
    {% with comments.count as total_comments %}
        <h2>{{ total_comments }} comment{{ total_comments|pluralize }}</h2>
    {% endwith %}
    {% for comment in comments %}
        <div class="comment">
            <p class="info">
                Comment {{ forloop.counter }} by {{ comment.name }}
                {{ comment.created }}
            </p>
            {{ comment.body|linebreaks }}
        </div>
    {% empty %}
        <p>There are no comments.</p>
    {% endfor %}

    {% include "blog/post/includes/comment_form.html" %}

{% endblock %}

mysite/blog/templates/blog/post/includes/comment_form.html
<h2>Add a new comment</h2>
<form action="{% url "blog:post_comment" post.id %}" method="post">
    <div class="left">{{ form.name.as_field_group }}</div>
    <div class="left">{{ form.email.as_field_group }}</div>
    {{ form.body.as_field_group }}
    {% csrf_token %}
    <p>
        <input type="submit" value="Add comment" />
    </p>
</form>

mysite/blog/templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
        <li>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </li>
    {% endfor %}
</ul>

mysite/blog/templates/blog/post/list.html
{% extends "blog/base.html" %}

{% load blog_tags %}

{% block title %}My Blog{% endblock %}
{% block content %}
    <h1>My Blog</h1>
    {% if tag %}<h2>Posts tagged with "{{ tag.name }}"</h2>{% endif %}
    {% for post in posts %}
        <h2>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </h2>
        <p class="tags">
            {% with post.tags.all as tags %}
                {% if tags %}Tags:{% endif %}
                {% for tag in tags %}
                    <a href="{% url "blog:post_list_by_tag" tag.slug %}">{{ tag.name }}</a>
                    {% if not forloop.last %},{% endif %}
                {% endfor %}
            {% endwith %}
        </p>
        <p class="date">Published {{ post.publish }} by {{ post.author }}</p>
        {{ post.body|markdown|truncatewords_html:20 }}
    {% endfor %}

    {% include "pagination.html" with page=posts %}

{% endblock %}

mysite/blog/templates/blog/post/search.html
{% extends "blog/base.html" %}

{% load blog_tags %}

{% block title %}Search{% endblock %}
{% block content %}
    {% if query %}
        <h1>Posts containing "{{ query }}"</h1>
        {% with results.count as total_results %}
            <h3>Found {{ total_results }} result{{ total_results|pluralize }}</h3>
        {% endwith %}
        {% for post in results %}
            <h4>
                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
            </h4>
            {{ post.body|markdown|truncatewords_html:12 }}
        {% empty %}
            <p>There are no results for your query.</p>
        {% endfor %}
        <p>
            <a href="{% url "blog:post_search" %}">Search again</a>
        </p>
    {% else %}
        <h1>Search for posts</h1>
        <form method="get">
            {{ form.as_p }}
            <input type="submit" value="Search" />
        </form>
    {% endif %}
{% endblock %}

mysite/blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %}Share a post{% endblock %}
{% block content %}
    {% if sent %}
        <h1>E-mail successfully sent</h1>
        <p>"{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.</p>
    {% else %}
        <h1>Share "{{ post.title }}" by e-mail</h1>
        <form method="post">
            {{ form.as_p }} {% csrf_token %}
            <input type="submit" value="Send e-mail" />
        </form>
    {% endif %}
{% endblock %}

mysite/blog/templates/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
        <span class="current">Page {{ page.number }} of {{ page.paginator.num_pages }}.</span>
        {% if page.has_next %}<a href="?page={{ page.next_page_number }}">Next</a>{% endif %}
    </span>
</div>